#!/bin/bash
set -e

unset PREFIX npm_config_prefix
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

link_workspace_dependency () {
  local dep_name="$1"
  local dep_path

  while IFS= read -r dep_path
  do
    rm -rf "$dep_path"
    ln -s "../../$dep_name" "$dep_path"
  done < <(find workspaces -maxdepth 3 -path "*/node_modules/$dep_name" -type d)
}

nvm use --delete-prefix

echo ">>>>> SETTING UP/RESETTING PROJECT"
mkdir -p workspaces
rm -rf workspaces/*

declare -a packages=(
  "mashlib"
  "solid-panes"
  "solid-ui"
  "pane-registry"
  "solid-logic"
  "rdflib"
  "pivot")

# Clone and npm install dependent packages
for package in "${packages[@]}"
do
  echo ""
  echo "# Installing $package"
  npm run add $package
done

link_workspace_dependency "rdflib"
link_workspace_dependency "solid-logic"

# Build dependent packages, ensuring each is in proper Node environment via nvm
for package in "${packages[@]}"
do
  echo ""
  echo "# Building $package"
  pushd workspaces/$package
  nvm use --delete-prefix
  npm run build
  if [[ "$package" == "rdflib" ]]; then
    npm run build:types
  fi
  popd
done

openssl req -outform PEM -keyform PEM -new -x509 -sha256 -newkey rsa:2048 -nodes -keyout workspaces/privkey.pem -days 365 -out workspaces/fullchain.pem -subj "/C=RO/ST=Bucharest/L=Bucharest/O=IT/CN=localhost"
